# Generated by Django 5.1.6 on 2025-04-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
