# Generated by Django 5.1.6 on 2025-04-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_user_users_rename_user_order_users_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='users',
            new_name='user',
        ),
    ]
